### ISSUE TITLE
New game fails on first roll of the dice

### ISSUE THREAD

**Issue by tezit** [levalleux-ludo/crypto-fantazia#1]
Started a new game with 3 players. The setup seemed to go well with each player displayed with the correct balance of 1500 newly minted tokens. But on the first roll immediately received a red error banner, while the roll returned a value of 12 and the position did move. I ignored the error since the result seemed correct, and as it was a "doubles" roll it asked player one to roll again. On second roll, the game state does not change and the error banner appears again with the following content

`{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":500,"statusText":"Internal Server Error","url":"http://191.101.165.97:4444/game/daa8a00a-0b79-4210-84e3-563c49d5e7e3/rollDices/tz1aTffQWtxsVnHz3NzhLJVGpoFqZ5S64uaw","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://191.101.165.97:4444/game/daa8a00a-0b79-4210-84e3-563c49d5e7e3/rollDices/tz1aTffQWtxsVnHz3NzhLJVGpoFqZ5S64uaw: 500 Internal Server Error","error":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Error: Player tz1aTffQWtxsVnHz3NzhLJVGpoFqZ5S64uaw is already playing<br> &nbsp; &nbsp;at GameService.&lt;anonymous&gt; (/home/ubuntu/crypto-fantazia/api/build/api/src/game.service.js:460:35)<br> &nbsp; &nbsp;at step (/home/ubuntu/crypto-fantazia/api/build/api/src/game.service.js:33:23)<br> &nbsp; &nbsp;at Object.next (/home/ubuntu/crypto-fantazia/api/build/api/src/game.service.js:14:53)<br> &nbsp; &nbsp;at fulfilled (/home/ubuntu/crypto-fantazia/api/build/api/src/game.service.js:5:58)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:68:7)</pre>\n</body>\n</html>\n"}`

Game setup details
Session Id: daa8a00a-0b79-4210-84e3-563c49d5e7e3
Smart Contracts:
Main: KT1ALy92yeub7W4oehGXCQRavu3KB8NhQuKn
Token: KT1WuzMkDucah6MrRmK7Qv36CWEZcJEixaQ7
Assets: KT1Wvpx98xRmcQ7yYyEYGP3Wr55U4GR9GQTm
Chance: KT1RSmTSwvWzuib7AiYK7ze68dmEQwqeqhLS
Community: KT1HydQtatgnUYp8UibNf5CCbNMC8Qe5Jj24

**Comment by tezit** [comment]
Thanks for addressing this, I will add a new issue regarding the gas limits
